### ISSUE TITLE
Question about Rio-Server

### ISSUE THREAD

**Issue by Ben1015** [SolidStateGroup/rio#9]
Hello everybody,

When i run the server (npm run server) with output a video url to the console, i have this message : 
`YouTube Download started
filename: Obstruction - A very short animation-wS8ZC271eMQ.3gp
size: 124021
An error occurred: Cannot find ffmpeg
ffmpeg standard output:
undefined
ffmpeg standard error:
undefined`
Any idea for resolve this?

Is it possible to stream a VLC-url?
It is possible to have the rio-server and ther server.py on the same raspberry?

Thanks for all.

**Comment by ssg-luke** [comment]
Hi @Ben1015,

You will need to have ffmpeg built/installed on your system in order to use the video output on rio. Assuming you are using a RPi running a Debian distrib to run rio-server, this is the guide I used which seemed to work for me https://owenashurst.com/?p=242.

It is not currently possible to stream a VLC url through rio-sever. You can run rio-server and server.py on the same RPi.

Cheers

**Comment by kyle-ssg** [comment]
I'm going to close this as the above comment answers the question. I'll amend the rio-server documentation to include video input support.

Regarding VLC compatibility, I'd suggest this is a candidate for a pull request as a new rio-server "input" if anyone has the desire to implement.
